### ISSUE TITLE
Reviews not working for fedimints

### ISSUE THREAD

**Issue by Kodylow** [MakePrisms/bitcoinmints#20]
the button is disabled for fedimint reviews unless the cashu url is filled , for fedimint reviews shouldn't be required
 
![image](https://github.com/user-attachments/assets/6b4715ee-8a93-4816-a2be-4adf1d161ddd)

**Comment by gudnuf** [comment]
Looks like the issue is I'm putting the fed pubkey in the "Federation Invite Code" field:
```jsx
value={mintType === Nip87MintTypes.Cashu ? mintUrl : mintPubkey}
```

And disabling based on invite code:
```jsx
            disabled={!inviteCode && !mintUrl}

```

Should that input be the pubkey or invite code?

**Comment by Kodylow** [comment]
use the inviteCode, the federationId is a hash of part of the config file it's not useful as a human level identifier
